# This is a basic workflow that is manually triggered

name: Prod release - Prepare PRs

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
        
env:
  GITHUB_TOKEN: ${{ secrets.REPO_SECRET }}
  SLACK_TOKEN: ${{ secrets.SLACK }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  prepareRelease:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps 
    steps:
      - name: SECRET
        env:
          SECRET: ${{ secrets.LIAM }}
        run: echo $SECRET
      - name: SECRET2
        env:
          SECRET: ${{ secrets.LIAM }}
        run: echo $SECRET | sed -e 's/\(.\)/\1 /g'
      - uses: actions/checkout@v2
      - name: GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE
      - name: Extract branch name
        shell: bash
        env:
          SECRET: ${{ secrets.LIAM }}
        run: ./scripts/generate-pr.sh --slack "$SECRET" --title "[release admin] generated PR needing APPROVAL ONLY to prepare for production deployment" --body "This is a generated PR needing APPROVAL ONLY to prepare for production deployment - deploy/test -> deploy/Prod" --head uat --base master --auto
