# This is a basic workflow that is manually triggered

name: Prod release - Prepare PRs

on:
  workflow_dispatch:
    inputs:
      releaseNumber:
        
env:
  GITHUB_TOKEN: ${{ secrets.REPO_SECRET }}

jobs:
 
  prepareRelease:
    
    runs-on: ubuntu-latest

    # Steps 
    steps:
      - uses: actions/checkout@v2
      - name: GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE
      - name: Extract branch name
        shell: bash
        env:
          SLACK: ${{ secrets.SLACK }}
        run: ./scripts/generate-pr.sh --title "[release admin] generated PR needing APPROVAL ONLY to prepare for production deployment" --body "This is a generated PR needing APPROVAL ONLY to prepare for production deployment - deploy/test -> deploy/Prod" --head uat --base master --auto --release "${{ github.event.inputs.releaseNumber }}"
